### ISSUE TITLE
$person should be $responsePerson

### ISSUE THREAD

**Issue by arnoutvandervorst** [Tools4everBV/HelloID-Conn-Prov-Target-Topdesk#1]
https://github.com/Tools4everBV/HelloID-Conn-Prov-Target-Topdesk/blob/456a029f44a1e92abb34fd540021cd359614127c/update.ps1#L253

**Comment by Rick-Jongbloed** [comment]
thanks. You could have a look in the V2 branch if this is still the case. We're releasing the new connector in approx, a month.
