### ISSUE TITLE
Person incorrectly archived on update

### ISSUE THREAD

**Issue by Rick-Jongbloed** [Tools4everBV/HelloID-Conn-Prov-Target-Topdesk#11]
The person is archived when the manager doesn't have an active contract. How exactly I don't know yet, but I have been able to reproduce this. Probably the manager and the person are mixed up in the archiving actions.
Related to TOPdesk ticket 20230620-054.

**Comment by bvandervoorn** [comment]
Ik zie dat hier gechecked wordt of de manager gearchiveerd moet worden. Dan wordt $shouldArchive op $true gezet. (rgl 813)
Daarna wordt gekekeken of de persoon zelf gearchiveerd moet worden. Dan wordt $shouldArchive weer op $true gezet. (rgl 865)
Hiertussenin wordt dit niet op false gezet, maar er wordt wel een if statement gemaakt ($shouldArchive -and $TopdeskPerson.status -ne 'personArchived'). Dit zorgt er dus voor dat als de manager gearchiveerd is, of wordt de gebruiker ook gearchiveerd wordt.
 
Ik denk dat dit een fout is en dit wil ik om 10 uur gaan herstellen bij beuningen.helloid.com. 
 
Mijn voorstel voor de oplossing is het scheiden van de $shouldArchive variabele naar:
$managerShouldArchive
$personShouldArchive
