### ISSUE TITLE
Create account script: Manager assignment when mRef is empty is not working

### ISSUE THREAD

**Issue by Rick-Jongbloed** [Tools4everBV/HelloID-Conn-Prov-Target-Topdesk#13]
Manager assignment when mRef is empty is not working in create script.

**Comment by rhouthuijzen** [comment]
Could not reproduce the problem. But found some issues in the code after reviewing it.

How the code works (also befor rework):
If mRef is empty the code will try to find the manager in Topdesk with the employeeNumber as correlation attribute ($p.PrimaryManager.ExternalId)
