### ISSUE TITLE
# HelloID-Conn-Prov-Target-Topdesk-Create # Version: 2.0.2 issues

### ISSUE THREAD

**Issue by ovanhooff** [Tools4everBV/HelloID-Conn-Prov-Target-Topdesk#18]
The problem is that the **$topdeskperson** variable is not being populated when the dry run flag is set to true. This will result in an error in lines 1054 - 1057 and in $result (line 1089) if the preview button is used.

**Comment by rhouthuijzen** [comment]
@ovanhooff thanks for reporting, we have a pull request ready that will resolve this issue.

The accountRefference is now also mandatory in the preview
