### ISSUE TITLE
Correlation

### ISSUE THREAD

**Issue by mouki9** [Tools4everBV/HelloID-Conn-Prov-Target-Topdesk#28]
Since the release of HelloID 2024.09 it is now possible to select the person account data of dependend systems as the person correlation field. The correlation configuration for this connector, but also goes for most of the powershell V2 connectors are only using the account field. Could the logic be changed so the actual person field is used for correlation? 

In the PowerShell code the correlation in several functions are not using the configuration, but is hardcoded on employeeNumber. This should also be fixed.

**Comment by rhouthuijzen** [comment]
@mouki9 as discussed this issue will automatically be resolved when we get the possibility to import entitlements. Then the manager Aref should always be used.

I will close this issue for now
