### ISSUE TITLE
OFS not supported in PowerShell core 7

### ISSUE THREAD

**Issue by berminatorrr** [Tools4everBV/HelloID-Conn-Prov-Target-Topdesk#5]
'ofs' in the The Get-RandomCharacters function is not supported in PowerShell core 7 (cloud agent). Please adjust this function. 

Remove the ofs-part from the function.

**Comment by rhouthuijzen** [comment]
Thank you for reporting this issue. This has now been fixed in the latest branch. If you have any questions, please let us know.
